version: 1.0.{build}

cache:
  - packages -> **\packages.config

install: 
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - nuget restore 
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build_script:
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test:
  assemblies: src\Tests\**\*test*.dll

after_test:
  - ps: Vsix-PushArtifacts -publishToGallery "src\SonarLint.Vsix\bin\Release\SonarLint.vsix"

notifications:
- provider: HipChat
  from: AppVeyor
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
