version: 1.0.{build}

cache:
  - packages -> **\packages.config

install: 
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - nuget restore 
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build_script:
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test:
  assemblies: src\Tests\**\*test*.dll

after_test:
  - ps: Vsix-PushArtifacts -publishToGallery "src\SonarLint.Vsix\bin\Release\SonarLint.vsix"
